In [279]:
import numpy as np

In [280]:
a = np.array([1,2,3])
b = np.array([[1000,400,1200],
              [1000,400,1200],
              [1000,400,1200]])

In [281]:
np.dot(a,b)

array([6000, 2400, 7200])

In [369]:
y_pred = np.array([1,1,0,0,1])
y_test = np.array([0.3,0.7,1,0,0.5])

# Mean Square error

In [283]:
def mse(y_pred, y_test):
    total_error=0
    for i,j in zip(y_test,y_pred):
        print(j,' : ',i)
        error = j - i
        total_error=total_error+error
        print(total_error)
        #total_error=error
    #print('Total error: ',total_error)
    #total_error = total_error*total_error
    #total_error = total_error/len(y_pred)
    #print("Mean Square error", total_error)

In [284]:
def mae(y_pred,y_test):
    total_error = 0
    for i in range (len(y_test)):
        total_error += y_pred[i]-y_test[i]
        total_error = abs(total_error)
    return total_error/len(y_pred)
mae(y_pred,y_test)

0.1

In [285]:
a = abs(sum(y_pred-y_test))
a = a/len(y_pred)
print (a)

0.1


In [286]:
def mae(y_pred, y_test):
    total_error = 0
    total_error = abs(sum(y_pred-y_test))
    print("Total error: ",total_error)
    error = np.mean(abs(y_pred-y_test))
    print(error)
    mae= total_error/len(y_pred)
    print("Mean Square: ",mae)

In [287]:
mae(y_pred, y_test)

Total error:  0.5
0.5
Mean Square:  0.1


In [288]:
mse(y_pred, y_test)

1  :  0.3
0.7
1  :  0.7
1.0
0  :  1.0
0.0
0  :  0.0
0.0
1  :  0.5
0.5


In [289]:
np.log(y_pred)

C:\Users\mehdi\AppData\Local\Temp\ipykernel_8888\4184140517.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_pred)


array([  0.,   0., -inf, -inf,   0.])

In [291]:
eps = 1e-15


In [292]:
1-np.exp(-15)

0.9999996940976795

In [293]:
y_ne_p = [max(i,eps) for i in (y_pred) ]
y_ne_p

[1, 1, 1e-15, 1e-15, 1]

In [294]:
y_ne_p =np.array([min(i,1-eps) for i in y_ne_p])
y_ne_p

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [295]:
np.log(y_ne_p)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [296]:
-np.mean(y_test*np.log(y_ne_p)+(1-y_test)*np.log(1-y_ne_p))

17.2696280766844

# Proper form of log function

In [327]:
def log_loss(y_test,y_pred):
    eps=1e-15
    total_error = 0
    y_ne_p = [max(i,eps) for i in (y_pred) ]
    y_ne_p =np.array([min(i,1-eps) for i in y_ne_p])
    return -np.mean(y_test*np.log(y_ne_p)+(1-y_test)*np.log(1-y_ne_p))
    

In [328]:
a = log_loss(y_test,y_pred)

In [329]:
print(a)

17.2696280766844


In [373]:
def log_loss(y_test,y_pred):
    eps=1e-15
    total_error = 0
    y_ne_p = [max(i,eps) for i in (y_pred) ]
    y_ne_p =np.array([min(i,1-eps) for i in y_ne_p])
    total_error = -sum(y_test*np.log(y_ne_p)+(1-y_test)*np.log(1-y_ne_p))
    return total_error/len(y_test)
    

In [374]:
a = log_loss(y_test,y_pred)

In [375]:
a

17.2696280766844