In [87]:
import numpy as np

In [88]:
inputs = [
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]
]


w = [
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
b = [2,3,0.5]

output = np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]    
])


type(w[0][0])

float

In [146]:
np.random.seed(0)

#Dense layer
class Layer_dense:
    def __init__(self,input_shape,neuron_shape):
        self.weights =0.1* np.random.randn(input_shape,neuron_shape)#instead of transposing again and again take weights differently from input shape
        self.bias = 1e-10+np.zeros((1,neuron_shape))
    #feedforward function    
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.bias

#Relu activation
class activation_Relu:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

#Sigmoid acti...
class activation_Sigmoid:
    def forward(self,inputs):
        self.output = 1/(1+np.exp(-inputs))   

        
#Softmax acti...        
class activation_Softmax:
    def forward(self,inputs):
        Inputs = np.max(inputs,axis = 1)
        Size = Inputs.size
        New_shape = Inputs.reshape(Size,1)
        inputs = inputs - New_shape
        exp = np.exp(inputs)
        add = np.sum(exp,axis=1)
        size = add.size
        add = add.reshape(size,1)
        self.output = exp/add

        
'''class Cost:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
'''    

class Categorical_Cross:
    def forward(self,y_pred,y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred,1e-7,1-1e-7)
        if len(y_true.shape)==1:
            correct_values = y_pred_clipped[range(samples),y_true]
        elif len(y_true.shape)==2:
            correct_values = np.sum(y_pred_clipped*y_true,axis=1)
            
        log_loss = -np.log(correct_values)
        return log_loss
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
        

In [147]:
layer_01 = Layer_dense(4,3)
layer_01.forward(inputs)
print(layer_01.output)


activati1 = activation_Relu()
activati1.forward(layer_01.output)
activati1.output

[[ 1.01226003  0.40413105  0.23502094]
 [ 1.46036793  1.05775487  0.00828524]
 [ 0.62111461  0.38274571 -0.56107983]]


array([[1.01226003, 0.40413105, 0.23502094],
       [1.46036793, 1.05775487, 0.00828524],
       [0.62111461, 0.38274571, 0.        ]])

In [148]:
layer_2 = Layer_dense(3,3)
layer_2.forward(activati1.output)
print(layer_2.output)



act = activation_Softmax()
act.forward(layer_2.output)
print(act.output)


[[ 0.09787937  0.05262401 -0.02336119]
 [ 0.14669346  0.17509833  0.04100443]
 [ 0.06004041  0.06474265  0.01971665]]
[[0.35191761 0.33634644 0.31173595]
 [0.34146982 0.35130829 0.30722189]
 [0.33724632 0.33883587 0.32391781]]


In [149]:
loss = Categorical_Cross()
loss.calculate(act.output,output)

1.0575629266129727