In [470]:
import numpy as np
import pandas as pd
from tensorflow import keras
import matplotlib.pyplot as plt

In [471]:
df = pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [472]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               28 non-null     int64
 1   affordibility     28 non-null     int64
 2   bought_insurance  28 non-null     int64
dtypes: int64(3)
memory usage: 800.0 bytes


In [420]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df[['age','affordibility']],df.affordibility,test_size=0.2,random_state=25)

In [421]:
len(X_train)

22

In [422]:
X_train.head()

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1

In [423]:
len(X_test)

6

In [424]:
X_train_scale = X_train.copy()
X_train_scale['age'] = X_train['age']/100
print(X_train_scale)
X_test_scale = X_test.copy()
X_test_scale['age'] = X_test['age']/100
print(X_test_scale)

     age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1
     age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1


In [374]:
model5 = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation = 'sigmoid',kernel_initializer = 'ones',bias_initializer='zeros')
])

In [375]:
model5.compile(optimizer = 'adam',
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])

In [376]:
model5.fit(X_train_scale,y_train,epochs=450)

Epoch 1/450
1/1 [==============================] - 6s 6s/step - loss: 0.4636 - accuracy: 0.6364
Epoch 2/450
1/1 [==============================] - 0s 56ms/step - loss: 0.4634 - accuracy: 0.6364
Epoch 3/450
1/1 [==============================] - 0s 16ms/step - loss: 0.4631 - accuracy: 0.6364
Epoch 4/450
1/1 [==============================] - 0s 32ms/step - loss: 0.4629 - accuracy: 0.6364
Epoch 5/450
1/1 [==============================] - 0s 16ms/step - loss: 0.4626 - accuracy: 0.6364
Epoch 6/450
1/1 [==============================] - 0s 16ms/step - loss: 0.4624 - accuracy: 0.6364
Epoch 7/450
1/1 [==============================] - 0s 32ms/step - loss: 0.4622 - accuracy: 0.6364
Epoch 8/450
1/1 [==============================] - 0s 32ms/step - loss: 0.4619 - accuracy: 0.6364
Epoch 9/450
1/1 [==============================] - 0s 16ms/step - loss: 0.4617 - accuracy: 0.6364
Epoch 10/450
1/1 [==============================] - 0s 32ms/step - loss: 0.4614 - accuracy: 0.6364
Epoch 11/450
1/1 [===

1/1 [==============================] - 0s 16ms/step - loss: 0.4265 - accuracy: 0.6364
Epoch 167/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4263 - accuracy: 0.6364
Epoch 168/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4261 - accuracy: 0.6364
Epoch 169/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4259 - accuracy: 0.6364
Epoch 170/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4257 - accuracy: 0.6364
Epoch 171/450
1/1 [==============================] - 0s 16ms/step - loss: 0.4255 - accuracy: 0.6364
Epoch 172/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4253 - accuracy: 0.6818
Epoch 173/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4251 - accuracy: 0.6818
Epoch 174/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4249 - accuracy: 0.6818
Epoch 175/450
1/1 [==============================] - 0s 8ms/step - loss: 0.4247 - accuracy: 0.6818
Epoch 176/450
1/1 [===

1/1 [==============================] - 0s 8ms/step - loss: 0.3952 - accuracy: 0.8636
Epoch 331/450
1/1 [==============================] - 0s 8ms/step - loss: 0.3951 - accuracy: 0.8636
Epoch 332/450
1/1 [==============================] - 0s 8ms/step - loss: 0.3949 - accuracy: 0.8636
Epoch 333/450
1/1 [==============================] - 0s 8ms/step - loss: 0.3947 - accuracy: 0.8636
Epoch 334/450
1/1 [==============================] - 0s 8ms/step - loss: 0.3945 - accuracy: 0.8636
Epoch 335/450
1/1 [==============================] - 0s 8ms/step - loss: 0.3944 - accuracy: 0.8636
Epoch 336/450
1/1 [==============================] - 0s 16ms/step - loss: 0.3942 - accuracy: 0.8636
Epoch 337/450
1/1 [==============================] - 0s 16ms/step - loss: 0.3940 - accuracy: 0.8636
Epoch 338/450
1/1 [==============================] - 0s 24ms/step - loss: 0.3938 - accuracy: 0.8636
Epoch 339/450
1/1 [==============================] - 0s 16ms/step - loss: 0.3937 - accuracy: 0.8636
Epoch 340/450
1/1 [=

In [377]:
model5.evaluate(X_test_scale,y_test)

1/1 [==============================] - 1s 560ms/step - loss: 0.2924 - accuracy: 1.0000


[0.2923941910266876, 1.0]

In [378]:
X_test_scale

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [379]:
model5.predict(X_test_scale)

1/1 [==============================] - 1s 680ms/step


array([[0.80090123],
       [0.7689195 ],
       [0.4499167 ],
       [0.7803384 ],
       [0.80297935],
       [0.81510425]], dtype=float32)

In [380]:
coef,intercept = model5.get_weights()
coef,intercept

(array([[0.6541948],
        [1.4555631]], dtype=float32),
 array([-0.3710979], dtype=float32))

In [425]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
sigmoid(18)

0.9999999847700205

In [426]:
intercept

array([-0.3710979], dtype=float32)

In [427]:
def prediction_fuc(age,afford):
    y_new=(age*coef[0])+(afford*coef[1]) + intercept
    return sigmoid(y_new)


In [428]:
prediction_fuc(.47,1)

array([0.8009013], dtype=float32)

In [429]:
def log_loss(y_test,y_pred):
    eps=1e-15
    total_error = 0
    y_ne_p = [max(i,eps) for i in (y_pred) ]
    y_ne_p =[min(i,1-eps) for i in y_ne_p]
    y_ne_p = np.array(y_ne_p)
    return  -np.mean(y_test*np.log(y_ne_p)+(1-y_test)*np.log(1-y_ne_p))

In [641]:
class ournn:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.b = 0
    
    def predict(self,X_test):
        Y_pred = self.w1*X_test['age']+self.w2*X_test['affordibility'] + self.b
        return sigmoid(Y_pred)
        
        
    def gradient_descent(self,age,affordibility,y_true,epochs,threshold):
        w1 =1
        w2= 1
        b= 0
        rate = 0.5
        n=len(age)
        c=10
    
        for i in range(epochs):
            y1_new = w1*age + w2*affordibility + b
            y_pred = sigmoid(y1_new)
            
            a = log_loss(y_train,y_pred)
            
            w1d = (1/n)*np.dot(np.transpose(age) ,(y_pred-y_train))
            w2d = (1/n)*np.dot(np.transpose(affordibility) ,(y_pred-y_train))
            
            bias_d = np.mean(y1_new-y_train)
            
            w1 = w1- rate*w1d
            w2 = w2- rate*w2d
            
            b = b - rate*bias_d
            
            print(f"Epoch:{i}, w1:{w1}, w2:{w2}, bias{b}, loss:{a}")
            if a <= threshold:
                break
        return w1,w2,b
        
    def fit(self,x,y,epochs,loss_threshold):
        self.w1, self.w2, self.b = self.gradient_descent(X_train_scale['age'],X_train_scale['affordibility'],y,epochs,loss_threshold)



In [570]:
def gradient_descent(age,affordibility,epochs,y_true,threshold):
    w1 =1
    w2= 1
    b= 0
    rate = 0.5
    n=len(age)
    c=10
    
    for i in range(epochs):
        y1_new = w1*age + w2*affordibility + b
        y_pred = sigmoid(y1_new)
        
        a = log_loss(y_train,y_pred)
        
        w1d = (1/n)*np.dot(np.transpose(age) ,(y_pred-y_train))
        w2d = (1/n)*np.dot(np.transpose(affordibility) ,(y_pred-y_train))
        
        bias_d = np.mean(y1_new-y_train)
        
        w1 = w1- rate*w1d
        w2 = w2- rate*w2d
        
        b = b - rate*bias_d

        print(f"Epoch:{i}, w1:{w1}, w2:{w2}, bias{b}, loss:{a}")
        return w1,w2,b
        
        

In [571]:
0.01*0.9

0.009000000000000001

In [646]:
gradient_descent(X_train_scale['age'],X_train_scale['affordibility'],1000,y_train,0.3)

Epoch:0, w1:0.9851349061974497, w2:1.0619844890308925, bias-0.20181818181818179, loss:0.4636130506450689


(0.9851349061974497, 1.0619844890308925, -0.20181818181818179)

In [651]:
custom_model = ournn()
custom_model.fit(X_train_scale, y_train,epochs = 1000, loss_threshold = 0.1)

Epoch:0, w1:0.9851349061974497, w2:1.0619844890308925, bias-0.20181818181818179, loss:0.4636130506450689
Epoch:1, w1:0.9767620694589888, w2:1.1315510270237485, bias-0.31944956394240565, loss:0.44021726313469595
Epoch:2, w1:0.9715577874694086, w2:1.2039483363577563, bias-0.39871027186048236, loss:0.42450537890914236
Epoch:3, w1:0.9679118102812923, w2:1.276849377378461, bias-0.4603258146060807, loss:0.4110716000298485
Epoch:4, w1:0.9650865190159501, w2:1.349204581280816, bias-0.5135935472711387, loss:0.39862734636980424
Epoch:5, w1:0.9627510834906808, w2:1.4205667380735627, bias-0.5626793287899571, loss:0.38683046616794226
Epoch:6, w1:0.9607579315625934, w2:1.4907604400055416, bias-0.609457026995595, loss:0.3755674287235074
Epoch:7, w1:0.9590407692972288, w2:1.559730387198094, bias-0.6547779815058297, loss:0.36478650800577017
Epoch:8, w1:0.9575689805486959, w2:1.6274735503164588, bias-0.6990368873922946, loss:0.3544554433207839
Epoch:9, w1:0.9563274174957417, w2:1.6940091601200873, bias-

In [652]:
custom_model.predict(X_test_scale)

2     0.915190
10    0.885757
21    0.088472
11    0.896795
14    0.916943
9     0.926785
dtype: float64

In [653]:
model.predict(X_test_scale)

1/1 [==============================] - 0s 198ms/step


array([[0.9957043 ],
       [0.99407023],
       [0.00718474],
       [0.99469376],
       [0.9957988 ],
       [0.99632406]], dtype=float32)

In [654]:
y_test

2     1
10    1
21    0
11    1
14    1
9     1
Name: affordibility, dtype: int64